"""Load a workspace off disk into a model the validators and the board generator share.

Parsing lives here, rules live in the callers. That split exists because three scripts
(`validate-workspace`, `board-gen`, and the gate helpers) must agree exactly on what a file
means; two parsers would disagree eventually, and the disagreement would surface as a board
that contradicts the validator.

Nothing here decides whether a workspace is *valid*. It reports what it could not read
(`load_errors`) and leaves every judgement to the caller. Standard library only (ADR-0002).
"""

from __future__ import annotations

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import frontmatter  # noqa: E402
import miniyaml  # noqa: E402
from record import (JOURNAL_HEADING_RE, entries,  # noqa: E402
                    sections as split_sections, table_rows)

__all__ = [
    "Workspace", "Item", "Question", "HistoryRow", "JournalEntry", "Doc",
    "TIMESTAMP_RE", "ID_PATTERNS", "id_kind", "find_workspace_root", "resolve_root",
    "WORKSPACE_MARKER",
]

# The *structures* — sections, blocks, tables, entries — live in `record.py`, which is the one
# place that decides where a bullet ends and what a labelled declaration is (F-069, F-073). This
# module is the workspace's *domain* model and reads them from there.

# The one file whose presence means "this directory is a workspace root". Scripts walk up to it
# rather than trusting the working directory: F-019 is a `cd` that changed what `.` meant
# mid-command, and the record then disagreed with the status in the one direction it could not
# detect.
WORKSPACE_MARKER = ("tracker", "project.yaml")


def find_workspace_root(start=None):
    """Return the nearest ancestor of `start` (default: CWD) that holds tracker/project.yaml."""
    current = os.path.abspath(start or os.getcwd())
    if os.path.isfile(current):
        current = os.path.dirname(current)
    while True:
        if os.path.isfile(os.path.join(current, *WORKSPACE_MARKER)):
            return current
        parent = os.path.dirname(current)
        if parent == current:
            return None
        current = parent


def resolve_root(explicit=None, announce=True, tool=""):
    """The root a script should act on.

    An explicit path is used verbatim — a caller who names a directory means that directory,
    even when it is not (yet) a workspace, which is what `workspace-init` and the
    not-yet-initialised validator run both need. With no explicit path the root is *found*,
    never assumed: walking up from CWD means running a script from inside `tracker/items/WI-0007`
    acts on the workspace, not on a fragment of it.
    """
    if explicit:
        return os.path.abspath(explicit)
    found = find_workspace_root()
    if found is None:
        return os.path.abspath(os.getcwd())
    if announce and found != os.path.abspath(os.getcwd()):
        print(f"{tool or 'agile-skills'}: workspace root resolved to {found} "
              f"(current directory is {os.getcwd()})", file=sys.stderr)
    return found

TIMESTAMP_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")

ID_PATTERNS = {
    "epic": re.compile(r"^EP-\d{3}$"),
    "work-item": re.compile(r"^WI-\d{4}$"),
    "bug": re.compile(r"^BUG-\d{4}$"),
}
QUESTION_ID_RE = re.compile(r"^Q-\d{3}$")
ADR_FILE_RE = re.compile(r"^ADR-\d{4}-[a-z0-9]+(-[a-z0-9]+)*\.md$")
AC_RE = re.compile(r"^\s*-\s+\[( |x|X)\]\s+(AC\d+)\s*(?:—|-|:)?\s*(.*)$")
# What a journal bullet *looks like* is this module's rule — a bolded label at the left margin.
# Where it *ends* is `record.py`'s (F-073). The two questions are separate and were being
# answered in one regex.
JOURNAL_BULLET_RE = re.compile(r"^-\s+\*\*(?P<label>[^*]+?):\*\*\s*(?P<value>.*)$")
BOARD_MARKER = "<!-- GENERATED by board-gen. Do not edit; run scripts/board-gen. -->"


def id_kind(identifier: str):
    """Return the item type implied by an ID prefix, or None."""
    for kind, pattern in ID_PATTERNS.items():
        if pattern.match(identifier or ""):
            return kind
    return None


class HistoryRow:
    __slots__ = ("when", "from_status", "to_status", "actor", "resume_to", "reason", "line")

    def __init__(self, cells: list, line: int) -> None:
        self.when, self.from_status, self.to_status, self.actor, self.resume_to, self.reason = (
            [cell.strip() for cell in cells] + [""] * (6 - len(cells))
        )[:6]
        self.line = line

    def normalised(self, value: str):
        """Treat the em-dash placeholder as absence."""
        return None if value in ("—", "-", "", "--") else value


class JournalEntry:
    __slots__ = ("when", "skill", "version", "persona", "bullets", "line")

    def __init__(self, when, skill, version, persona, line) -> None:
        self.when = when
        self.skill = skill
        self.version = version
        self.persona = persona
        self.bullets = {}
        self.line = line


class Question:
    __slots__ = ("path", "identifier", "fields", "body", "sections", "body_line")

    def __init__(self, path, identifier, fields, body, body_line) -> None:
        self.path = path
        self.identifier = identifier
        self.fields = fields
        self.body = body
        self.body_line = body_line
        self.sections = split_sections(body, body_line)

    @property
    def is_open(self) -> bool:
        return self.fields.get("status") == "open"

    @property
    def is_blocking(self) -> bool:
        return self.fields.get("blocking") is True


class Doc:
    __slots__ = ("path", "fields", "body", "sections", "body_line", "changelog", "corrections")

    def __init__(self, path, fields, body, body_line) -> None:
        self.path = path
        self.fields = fields
        self.body = body
        self.body_line = body_line
        self.sections = split_sections(body, body_line)
        self.changelog = table_rows(self.sections.get("## Change log", {}).get("text", ""),
                                      self.sections.get("## Change log", {}).get("line", 0))
        # `doc-header.md` §4b: the append-only repair record on a standing ADR. Same table shape
        # as the change log and a different question — the change log says a version happened,
        # this says what a sentence used to say.
        self.corrections = table_rows(self.sections.get("## Corrections", {}).get("text", ""),
                                        self.sections.get("## Corrections", {}).get("line", 0))


class Item:
    __slots__ = ("root", "identifier", "path", "fields", "body", "sections", "body_line",
                 "history", "journal", "questions", "artifacts")

    def __init__(self, root, identifier) -> None:
        self.root = root
        self.identifier = identifier
        self.path = os.path.join(root, "item.md")
        self.fields = {}
        self.body = ""
        self.body_line = 0
        self.sections = {}
        self.history = []
        self.journal = []
        self.questions = []
        self.artifacts = []

    @property
    def type(self):
        return self.fields.get("type")

    @property
    def status(self):
        return self.fields.get("status")

    @property
    def priority(self):
        return self.fields.get("priority")

    def artifact_path(self, name: str) -> str:
        return os.path.join(self.root, "artifacts", name)

    def has_artifact(self, name: str) -> bool:
        return os.path.isfile(self.artifact_path(name))

    def acceptance_criteria(self) -> list:
        section = self.sections.get("## Acceptance criteria")
        if not section:
            return []
        found = []
        line = section["line"]
        for raw in section["text"].split("\n"):
            line += 1
            match = AC_RE.match(raw)
            if match:
                found.append({
                    "label": match.group(2),
                    "checked": match.group(1).lower() == "x",
                    "text": match.group(3).strip(),
                    "line": line,
                })
        return found

    def statuses_reached(self) -> set:
        return {row.to_status for row in self.history}

    def open_questions(self) -> list:
        return [q for q in self.questions if q.is_open]

    def blocking_questions(self) -> list:
        return [q for q in self.questions if q.is_open and q.is_blocking]


class Workspace:
    """Everything the scripts need to know about one workspace, read once."""

    def __init__(self, root: str) -> None:
        self.root = os.path.abspath(root)
        self.tracker = os.path.join(self.root, "tracker")
        self.items_dir = os.path.join(self.tracker, "items")
        self.docs_dir = os.path.join(self.root, "docs")
        self.project = None
        self.project_path = os.path.join(self.tracker, "project.yaml")
        self.items = {}
        self.docs = []
        self.load_errors = []

    # ---- error collection ----------------------------------------------------------

    def fail(self, path, line, code, message, hint=""):
        self.load_errors.append((path, line, code, message, hint))

    # ---- loading -------------------------------------------------------------------

    def load(self) -> "Workspace":
        self.load_project()
        self.load_items()
        self.load_docs()
        return self

    def load_project(self) -> None:
        if not os.path.isfile(self.project_path):
            self.fail(self.project_path, 0, "project.missing",
                      "tracker/project.yaml does not exist",
                      hint="run scripts/workspace-init to create the workspace skeleton")
            return
        try:
            self.project = miniyaml.load_file(self.project_path)
        except miniyaml.YamlError as exc:
            self.fail(self.project_path, exc.line, "project.unparsable", exc.message)
            return
        if not isinstance(self.project, dict):
            self.fail(self.project_path, 1, "project.shape", "project.yaml must be a mapping")
            self.project = None

    def load_items(self) -> None:
        if not os.path.isdir(self.items_dir):
            self.fail(self.items_dir, 0, "items.missing", "tracker/items/ does not exist")
            return
        for name in sorted(os.listdir(self.items_dir)):
            directory = os.path.join(self.items_dir, name)
            if not os.path.isdir(directory):
                continue
            item = Item(directory, name)
            self.items[name] = item
            self.load_item_body(item)
            self.load_history(item)
            self.load_journal(item)
            self.load_questions(item)
            artifacts = os.path.join(directory, "artifacts")
            if os.path.isdir(artifacts):
                item.artifacts = sorted(os.listdir(artifacts))

    def load_item_body(self, item: Item) -> None:
        if not os.path.isfile(item.path):
            self.fail(item.path, 0, "item.missing", "item.md does not exist")
            return
        try:
            item.fields, item.body, item.body_line = frontmatter.load_file(item.path)
        except frontmatter.FrontmatterError as exc:
            self.fail(item.path, exc.line, "item.unparsable", exc.message)
            return
        item.sections = split_sections(item.body, item.body_line)

    def load_history(self, item: Item) -> None:
        path = os.path.join(item.root, "history.md")
        if not os.path.isfile(path):
            self.fail(path, 0, "history.missing", "history.md does not exist",
                      hint="it is created with its header when the item is created, so "
                           "'empty' and 'lost' stay distinguishable")
            return
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            text = handle.read()
        for cells, line in table_rows(text, 0):
            if len(cells) != 6:
                self.fail(path, line, "history.columns",
                          f"history row has {len(cells)} columns; the format has 6 "
                          f"(when, from, to, actor, resume-to, reason)")
                continue
            item.history.append(HistoryRow(cells, line))

    def load_journal(self, item: Item) -> None:
        path = os.path.join(item.root, "journal.md")
        if not os.path.isfile(path):
            self.fail(path, 0, "journal.missing", "journal.md does not exist")
            return
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            text = handle.read()
        for entry in entries(text, first_line=1, level=2):
            match = JOURNAL_HEADING_RE.match(entry.heading)
            if not match:
                self.fail(path, entry.line, "journal.heading",
                          f"entry heading does not match "
                          f"'## <timestamp> — <skill> v<version> — <persona>': "
                          f"{entry.heading.strip()!r}")
                continue
            current = JournalEntry(match.group("when"), match.group("skill"),
                                   match.group("version"), match.group("persona").strip(),
                                   entry.line)
            item.journal.append(current)
            for block in entry.blocks:
                if block.kind != "bullet" or block.indent != 0:
                    continue
                bullet = JOURNAL_BULLET_RE.match(block.lines[0])
                if bullet:
                    # `block.body` is the label's value with its continuation lines folded in.
                    # Reading only `bullet.group("value")` is F-073's second half: a wrapped
                    # bullet answers half the question it was asked.
                    current.bullets[bullet.group("label").strip()] = block.body

    def load_questions(self, item: Item) -> None:
        directory = os.path.join(item.root, "questions")
        if not os.path.isdir(directory):
            self.fail(directory, 0, "questions.missing",
                      "questions/ does not exist (it may be empty, but it must exist)")
            return
        for name in sorted(os.listdir(directory)):
            if not name.endswith(".md"):
                continue
            path = os.path.join(directory, name)
            try:
                fields, body, body_line = frontmatter.load_file(path)
            except frontmatter.FrontmatterError as exc:
                self.fail(path, exc.line, "question.unparsable", exc.message)
                continue
            item.questions.append(Question(path, name[:-3], fields, body, body_line))

    def load_docs(self) -> None:
        if not os.path.isdir(self.docs_dir):
            return
        for directory, dirs, files in os.walk(self.docs_dir):
            dirs[:] = [d for d in dirs if not d.startswith(".")]
            for name in sorted(files):
                if not name.endswith(".md"):
                    continue
                path = os.path.join(directory, name)
                try:
                    fields, body, body_line = frontmatter.load_file(path)
                except frontmatter.FrontmatterError as exc:
                    self.fail(path, exc.line, "doc.unparsable", exc.message)
                    continue
                self.docs.append(Doc(path, fields, body, body_line))

    # ---- convenience ---------------------------------------------------------------

    def epics(self) -> list:
        return [item for item in self.items.values() if item.type == "epic"]

    def children_of(self, epic_id: str) -> list:
        return [item for item in self.items.values() if item.fields.get("epic") == epic_id]

    def command(self, name: str):
        commands = (self.project or {}).get("commands") or {}
        return commands.get(name)

    def convention(self, name: str):
        conventions = (self.project or {}).get("conventions") or {}
        return conventions.get(name)

    def sorted_items(self) -> list:
        """Items in a stable order: epics first, then by ID."""
        return sorted(self.items.values(),
                      key=lambda item: (0 if item.type == "epic" else 1, item.identifier))
