"""Load a workspace off disk into a model the validators and the board generator share.

Parsing lives here, rules live in the callers. That split exists because three scripts
(`validate-workspace`, `board-gen`, and the gate helpers) must agree exactly on what a file
means; two parsers would disagree eventually, and the disagreement would surface as a board
that contradicts the validator.

Nothing here decides whether a workspace is *valid*. It reports what it could not read
(`load_errors`) and leaves every judgement to the caller. Standard library only (ADR-0002).
"""

from __future__ import annotations

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import frontmatter  # noqa: E402
import miniyaml  # noqa: E402
from record import (JOURNAL_HEADING_RE, blocks, entries,  # noqa: E402
                    sections as split_sections, table_rows)

__all__ = [
    "Workspace", "Item", "Question", "HistoryRow", "JournalEntry", "Doc", "PlanDocuments",
    "PlanRow", "TIMESTAMP_RE", "ID_PATTERNS", "id_kind", "find_workspace_root", "resolve_root",
    "plan_documents", "WORKSPACE_MARKER", "INVALIDATION_SECTION", "DELIVERABLE_SECTION",
    "BINDING_SECTION",
]

# The *structures* — sections, blocks, tables, entries — live in `record.py`, which is the one
# place that decides where a bullet ends and what a labelled declaration is (F-069, F-073). This
# module is the workspace's *domain* model and reads them from there.

# The one file whose presence means "this directory is a workspace root". Scripts walk up to it
# rather than trusting the working directory: F-019 is a `cd` that changed what `.` meant
# mid-command, and the record then disagreed with the status in the one direction it could not
# detect.
WORKSPACE_MARKER = ("tracker", "project.yaml")


def find_workspace_root(start=None):
    """Return the nearest ancestor of `start` (default: CWD) that holds tracker/project.yaml."""
    current = os.path.abspath(start or os.getcwd())
    if os.path.isfile(current):
        current = os.path.dirname(current)
    while True:
        if os.path.isfile(os.path.join(current, *WORKSPACE_MARKER)):
            return current
        parent = os.path.dirname(current)
        if parent == current:
            return None
        current = parent


def resolve_root(explicit=None, announce=True, tool=""):
    """The root a script should act on.

    An explicit path is used verbatim — a caller who names a directory means that directory,
    even when it is not (yet) a workspace, which is what `workspace-init` and the
    not-yet-initialised validator run both need. With no explicit path the root is *found*,
    never assumed: walking up from CWD means running a script from inside `tracker/items/WI-0007`
    acts on the workspace, not on a fragment of it.
    """
    if explicit:
        return os.path.abspath(explicit)
    found = find_workspace_root()
    if found is None:
        return os.path.abspath(os.getcwd())
    if announce and found != os.path.abspath(os.getcwd()):
        print(f"{tool or 'agile-skills'}: workspace root resolved to {found} "
              f"(current directory is {os.getcwd()})", file=sys.stderr)
    return found

TIMESTAMP_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")

ID_PATTERNS = {
    "epic": re.compile(r"^EP-\d{3}$"),
    "work-item": re.compile(r"^WI-\d{4}$"),
    "bug": re.compile(r"^BUG-\d{4}$"),
}
QUESTION_ID_RE = re.compile(r"^Q-\d{3}$")
ADR_FILE_RE = re.compile(r"^ADR-\d{4}-[a-z0-9]+(-[a-z0-9]+)*\.md$")
AC_RE = re.compile(r"^\s*-\s+\[( |x|X)\]\s+(AC\d+)\s*(?:—|-|:)?\s*(.*)$")
# What a journal bullet *looks like* is this module's rule — a bolded label at the left margin.
# Where it *ends* is `record.py`'s (F-073). The two questions are separate and were being
# answered in one regex.
JOURNAL_BULLET_RE = re.compile(r"^-\s+\*\*(?P<label>[^*]+?):\*\*\s*(?P<value>.*)$")
BOARD_MARKER = "<!-- GENERATED by board-gen. Do not edit; run scripts/board-gen. -->"


def id_kind(identifier: str):
    """Return the item type implied by an ID prefix, or None."""
    for kind, pattern in ID_PATTERNS.items():
        if pattern.match(identifier or ""):
            return kind
    return None


class HistoryRow:
    __slots__ = ("when", "from_status", "to_status", "actor", "resume_to", "reason", "line")

    def __init__(self, cells: list, line: int) -> None:
        self.when, self.from_status, self.to_status, self.actor, self.resume_to, self.reason = (
            [cell.strip() for cell in cells] + [""] * (6 - len(cells))
        )[:6]
        self.line = line

    def normalised(self, value: str):
        """Treat the em-dash placeholder as absence."""
        return None if value in ("—", "-", "", "--") else value


class JournalEntry:
    __slots__ = ("when", "skill", "version", "persona", "bullets", "line")

    def __init__(self, when, skill, version, persona, line) -> None:
        self.when = when
        self.skill = skill
        self.version = version
        self.persona = persona
        self.bullets = {}
        self.line = line


class Question:
    __slots__ = ("path", "identifier", "fields", "body", "sections", "body_line")

    def __init__(self, path, identifier, fields, body, body_line) -> None:
        self.path = path
        self.identifier = identifier
        self.fields = fields
        self.body = body
        self.body_line = body_line
        self.sections = split_sections(body, body_line)

    @property
    def is_open(self) -> bool:
        return self.fields.get("status") == "open"

    @property
    def is_blocking(self) -> bool:
        return self.fields.get("blocking") is True


class Doc:
    __slots__ = ("path", "fields", "body", "sections", "body_line", "changelog", "corrections")

    def __init__(self, path, fields, body, body_line) -> None:
        self.path = path
        self.fields = fields
        self.body = body
        self.body_line = body_line
        self.sections = split_sections(body, body_line)
        self.changelog = table_rows(self.sections.get("## Change log", {}).get("text", ""),
                                      self.sections.get("## Change log", {}).get("line", 0))
        # `doc-header.md` §4b: the append-only repair record on a standing ADR. Same table shape
        # as the change log and a different question — the change log says a version happened,
        # this says what a sentence used to say.
        self.corrections = table_rows(self.sections.get("## Corrections", {}).get("text", ""),
                                        self.sections.get("## Corrections", {}).get("line", 0))


class Item:
    __slots__ = ("root", "identifier", "path", "fields", "body", "sections", "body_line",
                 "history", "journal", "questions", "artifacts")

    def __init__(self, root, identifier) -> None:
        self.root = root
        self.identifier = identifier
        self.path = os.path.join(root, "item.md")
        self.fields = {}
        self.body = ""
        self.body_line = 0
        self.sections = {}
        self.history = []
        self.journal = []
        self.questions = []
        self.artifacts = []

    @property
    def type(self):
        return self.fields.get("type")

    @property
    def status(self):
        return self.fields.get("status")

    @property
    def priority(self):
        return self.fields.get("priority")

    def artifact_path(self, name: str) -> str:
        return os.path.join(self.root, "artifacts", name)

    def has_artifact(self, name: str) -> bool:
        return os.path.isfile(self.artifact_path(name))

    def acceptance_criteria(self) -> list:
        section = self.sections.get("## Acceptance criteria")
        if not section:
            return []
        found = []
        line = section["line"]
        for raw in section["text"].split("\n"):
            line += 1
            match = AC_RE.match(raw)
            if match:
                found.append({
                    "label": match.group(2),
                    "checked": match.group(1).lower() == "x",
                    "text": match.group(3).strip(),
                    "line": line,
                })
        return found

    def statuses_reached(self) -> set:
        return {row.to_status for row in self.history}

    def open_questions(self) -> list:
        return [q for q in self.questions if q.is_open]

    def blocking_questions(self) -> list:
        return [q for q in self.questions if q.is_open and q.is_blocking]


class Workspace:
    """Everything the scripts need to know about one workspace, read once."""

    def __init__(self, root: str) -> None:
        self.root = os.path.abspath(root)
        self.tracker = os.path.join(self.root, "tracker")
        self.items_dir = os.path.join(self.tracker, "items")
        self.docs_dir = os.path.join(self.root, "docs")
        self.project = None
        self.project_path = os.path.join(self.tracker, "project.yaml")
        self.items = {}
        self.docs = []
        self.load_errors = []

    # ---- error collection ----------------------------------------------------------

    def fail(self, path, line, code, message, hint=""):
        self.load_errors.append((path, line, code, message, hint))

    # ---- loading -------------------------------------------------------------------

    def load(self) -> "Workspace":
        self.load_project()
        self.load_items()
        self.load_docs()
        return self

    def load_project(self) -> None:
        if not os.path.isfile(self.project_path):
            self.fail(self.project_path, 0, "project.missing",
                      "tracker/project.yaml does not exist",
                      hint="run scripts/workspace-init to create the workspace skeleton")
            return
        try:
            self.project = miniyaml.load_file(self.project_path)
        except miniyaml.YamlError as exc:
            self.fail(self.project_path, exc.line, "project.unparsable", exc.message)
            return
        if not isinstance(self.project, dict):
            self.fail(self.project_path, 1, "project.shape", "project.yaml must be a mapping")
            self.project = None

    def load_items(self) -> None:
        if not os.path.isdir(self.items_dir):
            self.fail(self.items_dir, 0, "items.missing", "tracker/items/ does not exist")
            return
        for name in sorted(os.listdir(self.items_dir)):
            directory = os.path.join(self.items_dir, name)
            if not os.path.isdir(directory):
                continue
            item = Item(directory, name)
            self.items[name] = item
            self.load_item_body(item)
            self.load_history(item)
            self.load_journal(item)
            self.load_questions(item)
            artifacts = os.path.join(directory, "artifacts")
            if os.path.isdir(artifacts):
                item.artifacts = sorted(os.listdir(artifacts))

    def load_item_body(self, item: Item) -> None:
        if not os.path.isfile(item.path):
            self.fail(item.path, 0, "item.missing", "item.md does not exist")
            return
        try:
            item.fields, item.body, item.body_line = frontmatter.load_file(item.path)
        except frontmatter.FrontmatterError as exc:
            self.fail(item.path, exc.line, "item.unparsable", exc.message)
            return
        item.sections = split_sections(item.body, item.body_line)

    def load_history(self, item: Item) -> None:
        path = os.path.join(item.root, "history.md")
        if not os.path.isfile(path):
            self.fail(path, 0, "history.missing", "history.md does not exist",
                      hint="it is created with its header when the item is created, so "
                           "'empty' and 'lost' stay distinguishable")
            return
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            text = handle.read()
        for cells, line in table_rows(text, 0):
            if len(cells) != 6:
                self.fail(path, line, "history.columns",
                          f"history row has {len(cells)} columns; the format has 6 "
                          f"(when, from, to, actor, resume-to, reason)")
                continue
            item.history.append(HistoryRow(cells, line))

    def load_journal(self, item: Item) -> None:
        path = os.path.join(item.root, "journal.md")
        if not os.path.isfile(path):
            self.fail(path, 0, "journal.missing", "journal.md does not exist")
            return
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            text = handle.read()
        for entry in entries(text, first_line=1, level=2):
            match = JOURNAL_HEADING_RE.match(entry.heading)
            if not match:
                self.fail(path, entry.line, "journal.heading",
                          f"entry heading does not match "
                          f"'## <timestamp> — <skill> v<version> — <persona>': "
                          f"{entry.heading.strip()!r}")
                continue
            current = JournalEntry(match.group("when"), match.group("skill"),
                                   match.group("version"), match.group("persona").strip(),
                                   entry.line)
            item.journal.append(current)
            for block in entry.blocks:
                if block.kind != "bullet" or block.indent != 0:
                    continue
                bullet = JOURNAL_BULLET_RE.match(block.lines[0])
                if bullet:
                    # `block.body` is the label's value with its continuation lines folded in.
                    # Reading only `bullet.group("value")` is F-073's second half: a wrapped
                    # bullet answers half the question it was asked.
                    current.bullets[bullet.group("label").strip()] = block.body

    def load_questions(self, item: Item) -> None:
        directory = os.path.join(item.root, "questions")
        if not os.path.isdir(directory):
            self.fail(directory, 0, "questions.missing",
                      "questions/ does not exist (it may be empty, but it must exist)")
            return
        for name in sorted(os.listdir(directory)):
            if not name.endswith(".md"):
                continue
            path = os.path.join(directory, name)
            try:
                fields, body, body_line = frontmatter.load_file(path)
            except frontmatter.FrontmatterError as exc:
                self.fail(path, exc.line, "question.unparsable", exc.message)
                continue
            item.questions.append(Question(path, name[:-3], fields, body, body_line))

    def load_docs(self) -> None:
        if not os.path.isdir(self.docs_dir):
            return
        for directory, dirs, files in os.walk(self.docs_dir):
            dirs[:] = [d for d in dirs if not d.startswith(".")]
            for name in sorted(files):
                if not name.endswith(".md"):
                    continue
                path = os.path.join(directory, name)
                try:
                    fields, body, body_line = frontmatter.load_file(path)
                except frontmatter.FrontmatterError as exc:
                    self.fail(path, exc.line, "doc.unparsable", exc.message)
                    continue
                self.docs.append(Doc(path, fields, body, body_line))

    # ---- convenience ---------------------------------------------------------------

    def epics(self) -> list:
        return [item for item in self.items.values() if item.type == "epic"]

    def children_of(self, epic_id: str) -> list:
        return [item for item in self.items.values() if item.fields.get("epic") == epic_id]

    def command(self, name: str):
        commands = (self.project or {}).get("commands") or {}
        return commands.get(name)

    def convention(self, name: str):
        conventions = (self.project or {}).get("conventions") or {}
        return conventions.get(name)

    def sorted_items(self) -> list:
        """Items in a stable order: epics first, then by ID."""
        return sorted(self.items.values(),
                      key=lambda item: (0 if item.type == "epic" else 1, item.identifier))


# ---- the plan's document declarations (ADR-0010 §5) ---------------------------------------

# A path as it appears inside a plan's prose or a table cell: backticked, bolded, or bare, with
# or without a sentence around it. Read as "the first thing that looks like a document", because
# the row's own column is `document` and the rest of the line is the human's locating text.
_DOCUMENT_RE = re.compile(r"[A-Za-z0-9_][A-Za-z0-9_./\-]*\.md")
# The declared-empty sentinel. `plan`'s procedure: *"An empty set is written as one row saying
# `none`... an absent section is not an empty one."* The distinction is the whole point — a
# section somebody forgot and a section somebody answered are different facts, and a reader that
# collapses them is the F-066 shape one level up.
_NONE_RE = re.compile(r"^\W*none\b", re.IGNORECASE)

INVALIDATION_SECTION = "## Invalidation set"
DELIVERABLE_SECTION = "## Deliverable documents"
BINDING_SECTION = "## Binding ADRs"
_ADR_ID_RE = re.compile(r"\bADR-(\d{4})\b")


class PlanRow:
    """One row of the invalidation set, kept whole.

    The five cells are `document | what | kind | why | disposition` (ADR-0010 §5.1). They are
    carried rather than digested because two different gates ask two different questions of the
    same row — `plan` asks whether `kind` is one of three words, `implement` and `verify` ask
    whether `disposition` is one of four — and a reader that kept only the paths would send each
    of them off to parse the table again.
    """

    __slots__ = ("cells", "line", "document", "is_none")

    def __init__(self, cells, line, document, is_none) -> None:
        self.cells = list(cells)
        self.line = line
        self.document = document
        self.is_none = is_none

    def cell(self, index: int) -> str:
        return self.cells[index].strip() if index < len(self.cells) else ""

    @property
    def what(self) -> str:
        return self.cell(1)

    @property
    def kind(self) -> str:
        return self.cell(2)

    @property
    def disposition(self) -> str:
        return self.cell(4)

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"PlanRow({self.document!r}, line={self.line}, kind={self.kind!r})"


class PlanDocuments:
    """What `tracker/items/<ID>/artifacts/plan.md` says about documents (ADR-0010 §5.1).

    Three consumers read the same two sections and must read them identically: `lint-claims`
    (which widens its window by them), `check-verify-freshness` (which subtracts the deliverable
    ones from its `docs/` exemption), and whatever later gate checks dispositions. Parsing lives
    here for the reason the module docstring gives — two parsers disagree eventually.

    Nothing here judges. `errors` is a list of `(line, code, message)` the caller reports in its
    own voice; `declared_empty` says the plan *answered* `none` rather than saying nothing.
    """

    __slots__ = ("item", "path", "invalidation", "deliverable", "errors", "declared_empty",
                 "rows", "binding_adrs", "binding_unreadable", "present")

    def __init__(self, item, path) -> None:
        self.item = item
        self.path = path
        self.invalidation = []          # [(relative-path, line)]
        self.deliverable = []           # [(relative-path, line)]
        self.errors = []                # [(line, code, message)]
        self.declared_empty = set()     # section headings answered `none`
        # Read for the gates that judge the row rather than the path. Nothing here adds to
        # `errors`: `lint-claims` and `check-verify-freshness` were reading this object before
        # `## Binding ADRs` existed, and a new required section here would narrow their windows
        # for a reason that has nothing to do with either of them.
        self.rows = []                  # [PlanRow] - the invalidation table, whole
        self.binding_adrs = []          # [(ADR-nnnn, line)]
        self.binding_unreadable = []    # [(line, text)] - a line naming neither an ID nor `none`
        self.present = set()            # the section headings the plan actually has

    @property
    def documents(self) -> list:
        """Every document the plan names, either way, de-duplicated and ordered."""
        return sorted({path for path, _ in self.invalidation + self.deliverable})

    @property
    def readable(self) -> bool:
        return not self.errors


def _named_documents(text: str, line: int, heading: str, found: PlanDocuments,
                     rows) -> list:
    """Pull document paths out of one section, recording what could not be read."""
    named, said_none, saw_content = [], False, False
    for content, content_line in rows:
        if not content.strip():
            continue
        saw_content = True
        if _NONE_RE.match(content.strip()):
            said_none = True
            continue
        match = _DOCUMENT_RE.search(content)
        if match is None:
            found.errors.append((content_line, "plan.document.unreadable",
                                 f"{heading}: {content.strip()[:80]!r} names no document — a "
                                 f"row a reader cannot resolve to a path is a row a gate "
                                 f"silently drops from its scope"))
            continue
        named.append((match.group(0), content_line))
    if not saw_content:
        found.errors.append((line, "plan.section.empty",
                             f"{heading} is present but says nothing — write `none` if nothing "
                             f"applies; a section that answers nothing is not an answer"))
    elif said_none and named:
        found.errors.append((line, "plan.section.contradictory",
                             f"{heading} says `none` and also names {len(named)} document(s)"))
    if said_none and not named:
        found.declared_empty.add(heading)
    return named


def plan_documents(root: str, item_id: str) -> PlanDocuments:
    """Read an item plan's `## Invalidation set` and `## Deliverable documents` (ADR-0010 §5).

    An **absent** section is an error and not an empty set. That is not pedantry: the two
    sections are what tell a gate how wide its window is, so a plan that omits one gives every
    consumer a smaller scope than the item actually has and gives it silently — which is F-066's
    mechanism (a gate reporting a scope it did not have) moved one file upstream.
    """
    path = os.path.join(root, "tracker", "items", item_id, "artifacts", "plan.md")
    found = PlanDocuments(item_id, path)
    if not os.path.isfile(path):
        found.errors.append((0, "plan.missing",
                             f"{item_id} has no artifacts/plan.md, so the documents this change "
                             f"was permitted to touch are not declared anywhere"))
        return found
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            text = handle.read()
    except OSError as problem:
        found.errors.append((0, "plan.unreadable", f"{path} could not be read: {problem}"))
        return found

    # An item artifact carries no frontmatter (`spec/workspace-layout.md`), so the whole file
    # is the body and line 1 is line 1. `sections()` reads headings, so a plan that grew one
    # anyway would still parse.
    parts = split_sections(text, 1)

    for heading in (INVALIDATION_SECTION, DELIVERABLE_SECTION, BINDING_SECTION):
        if heading in parts:
            found.present.add(heading)

    section = parts.get(INVALIDATION_SECTION)
    if section is None:
        found.errors.append((0, "plan.section.missing",
                             f"{INVALIDATION_SECTION} is absent from {item_id}'s plan; an absent "
                             f"section is not an empty one (ADR-0010 §5.1)"))
    else:
        rows = []
        for cells, row_line in table_rows(section["text"], section["line"]):
            if len(cells) < 5:
                found.errors.append((row_line, "plan.row.malformed",
                                     f"{INVALIDATION_SECTION}: a row with {len(cells)} cell(s); "
                                     f"the shape is | document | what | kind | why | "
                                     f"disposition |"))
                continue
            rows.append((cells[0], row_line))
            match = _DOCUMENT_RE.search(cells[0])
            found.rows.append(PlanRow(cells, row_line,
                                      match.group(0) if match else "",
                                      bool(_NONE_RE.match(cells[0].strip()))))
        found.invalidation = _named_documents(section["text"], section["line"],
                                              INVALIDATION_SECTION, found, rows)

    section = parts.get(DELIVERABLE_SECTION)
    if section is None:
        found.errors.append((0, "plan.section.missing",
                             f"{DELIVERABLE_SECTION} is absent from {item_id}'s plan; an absent "
                             f"section is not an empty one (ADR-0010 §5.1)"))
    else:
        listed = [(block.joined, block.start)
                  for block in blocks(section["text"], section["line"])
                  if block.kind in ("bullet", "text")]
        found.deliverable = _named_documents(section["text"], section["line"],
                                             DELIVERABLE_SECTION, found, listed)

    section = parts.get(BINDING_SECTION)
    if section is not None:
        for block in blocks(section["text"], section["line"]):
            if block.kind not in ("bullet", "text"):
                continue
            text = block.joined.strip()
            if not text:
                continue
            named = _ADR_ID_RE.findall(text)
            if named:
                found.binding_adrs.extend((f"ADR-{number}", block.start) for number in named)
            elif _NONE_RE.match(text):
                found.declared_empty.add(BINDING_SECTION)
            else:
                found.binding_unreadable.append((block.start, text))
    return found
