#!/usr/bin/env bash
# Import a completed toy-project run into examples/toy-project/.
#
# Usage: examples/toy-project/import.sh <path-to-the-run-repository>
#
# Copies the source, the whole tracker/ and docs/, and turns the run's git history into text —
# because `.git` cannot be committed inside this repository (see meta/adr/ADR-0004). Files this
# directory owns (IDEA.md, HUMAN-SCRIPT.md, README.md, AUDIT.md, import.sh) are never touched.
#
# Idempotent: re-running after a re-executed run replaces the imported material wholesale.

set -euo pipefail

SOURCE="${1:?usage: import.sh <path-to-the-run-repository>}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

[ -d "$SOURCE/.git" ] || { echo "import: $SOURCE is not a git repository" >&2; exit 1; }
[ -d "$SOURCE/tracker" ] || { echo "import: $SOURCE has no tracker/" >&2; exit 1; }

echo "import: $SOURCE -> $HERE"

# --- the workspace and the code ----------------------------------------------------
rm -rf "$HERE/tracker" "$HERE/docs" "$HERE/src"
cp -r "$SOURCE/tracker" "$HERE/tracker"
[ -d "$SOURCE/docs" ] && cp -r "$SOURCE/docs" "$HERE/docs"

mkdir -p "$HERE/src"
# Everything the run produced that is not the workspace, the tooling, or git.
( cd "$SOURCE" && git ls-files ) | while read -r file; do
  case "$file" in
    tracker/*|docs/*|.claude/*|CONSUMER-PROMPT.md) continue ;;
  esac
  mkdir -p "$HERE/src/$(dirname "$file")"
  cp "$SOURCE/$file" "$HERE/src/$file"
done

# --- the history, as text ----------------------------------------------------------
{
  echo "# Git log — the toy project's real history"
  echo
  echo "Generated by \`examples/toy-project/import.sh\` from the run repository. The repository"
  echo "itself is not committed here; see \`meta/adr/ADR-0004-toy-project-execution.md\` for why,"
  echo "and \`GIT-BRANCHES.md\` for the per-item \`git log --grep\` output that Definition of Done"
  echo "D8 requires."
  echo
  echo '```text'
  ( cd "$SOURCE" && git log --all --graph --date-order --stat \
      --pretty=format:'%h %ad %an%n    %s%n' --date=iso-strict )
  echo
  echo '```'
} > "$HERE/GIT-LOG.md"

{
  echo "# Git branches, and each item's code history"
  echo
  echo "\`git log --grep <ITEM-ID>\` is what Definition of Done D8 requires to reconstruct an"
  echo "item's code history. This file is that command's output, per item, from the real run"
  echo "repository."
  echo
  echo "## Branches"
  echo
  echo '```text'
  ( cd "$SOURCE" && git branch -a --format='%(refname:short)  %(objectname:short)  %(contents:subject)' )
  echo '```'
  echo
  for item in $( cd "$SOURCE/tracker/items" && ls -d */ 2>/dev/null | tr -d '/' | sort ); do
    echo "## $item"
    echo
    echo '```text'
    echo "\$ git log --grep $item --oneline --all"
    ( cd "$SOURCE" && git log --grep "$item" --oneline --all ) || true
    echo '```'
    echo
  done
} > "$HERE/GIT-BRANCHES.md"

echo "import: wrote tracker/, docs/, src/, GIT-LOG.md, GIT-BRANCHES.md"
echo "import: now run  python3 scripts/validate-workspace examples/toy-project"
